# Generated by Django 5.2.8 on 2025-12-02 09:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="blogview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 12, 2, 9, 14, 18, 358884, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="country",
            name="continent",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 12, 2, 9, 14, 26, 850313, tzinfo=datetime.timezone.utc
                ),
                max_length=128,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="country",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 12, 2, 9, 14, 34, 536447, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="country",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True)),
                ("number_of_blogs", models.IntegerField(default=0)),
                ("number_of_views", models.IntegerField(default=0)),
                ("number_of_likes", models.IntegerField(default=0)),
                ("number_of_comments", models.IntegerField(default=0)),
                ("number_of_shares", models.IntegerField(default=0)),
                ("number_of_reactions", models.IntegerField(default=0)),
                ("number_of_followers", models.IntegerField(default=0)),
                ("number_of_following", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "ordering": ["-number_of_views"],
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="analytics.author",
            ),
        ),
        migrations.CreateModel(
            name="BlogCreationTimeSeriesAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("raw", "Raw"),
                            ("hour", "Hour"),
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        db_index=True,
                        help_text="Time granularity level (raw, hour, day, week, month, year)",
                        max_length=10,
                    ),
                ),
                (
                    "time_bucket",
                    models.DateTimeField(
                        db_index=True,
                        help_text="The start time of the aggregation bucket",
                    ),
                ),
                (
                    "blog_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of blogs created in this time bucket",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific author (null for all authors aggregate)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_creation_aggregates",
                        to="analytics.author",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific country (null for all countries aggregate)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_creation_aggregates",
                        to="analytics.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Creation Time Series Aggregate",
                "verbose_name_plural": "Blog Creation Time Series Aggregates",
                "ordering": ["-time_bucket", "granularity"],
                "indexes": [
                    models.Index(
                        fields=["granularity", "time_bucket"],
                        name="analytics_b_granula_af626c_idx",
                    ),
                    models.Index(
                        fields=["time_bucket", "granularity"],
                        name="analytics_b_time_bu_06162b_idx",
                    ),
                    models.Index(
                        fields=["country", "granularity", "time_bucket"],
                        name="analytics_b_country_0478da_idx",
                    ),
                    models.Index(
                        fields=["author", "granularity", "time_bucket"],
                        name="analytics_b_author__54bfad_idx",
                    ),
                ],
                "unique_together": {
                    ("granularity", "time_bucket", "country", "author")
                },
            },
        ),
        migrations.CreateModel(
            name="BlogViewTimeSeriesAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("raw", "Raw"),
                            ("hour", "Hour"),
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        db_index=True,
                        help_text="Time granularity level (raw, hour, day, week, month, year)",
                        max_length=10,
                    ),
                ),
                (
                    "time_bucket",
                    models.DateTimeField(
                        db_index=True,
                        help_text="The start time of the aggregation bucket",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0, help_text="Total number of views in this time bucket"
                    ),
                ),
                (
                    "unique_blogs_viewed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of distinct blogs viewed in this time bucket",
                    ),
                ),
                (
                    "unique_users",
                    models.IntegerField(
                        default=0,
                        help_text="Number of distinct users who viewed in this time bucket",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific author (null for all authors aggregate)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_time_series_aggregates",
                        to="analytics.author",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific blog (null for all blogs aggregate)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_time_series_aggregates",
                        to="analytics.blog",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific country (null for all countries aggregate)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="view_time_series_aggregates",
                        to="analytics.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog View Time Series Aggregate",
                "verbose_name_plural": "Blog View Time Series Aggregates",
                "ordering": ["-time_bucket", "granularity"],
                "indexes": [
                    models.Index(
                        fields=["granularity", "time_bucket"],
                        name="analytics_b_granula_413e87_idx",
                    ),
                    models.Index(
                        fields=["time_bucket", "granularity"],
                        name="analytics_b_time_bu_03cd0a_idx",
                    ),
                    models.Index(
                        fields=["blog", "granularity", "time_bucket"],
                        name="analytics_b_blog_id_c4c320_idx",
                    ),
                    models.Index(
                        fields=["country", "granularity", "time_bucket"],
                        name="analytics_b_country_ea2847_idx",
                    ),
                    models.Index(
                        fields=["author", "granularity", "time_bucket"],
                        name="analytics_b_author__144dc4_idx",
                    ),
                ],
                "unique_together": {
                    ("granularity", "time_bucket", "blog", "country", "author")
                },
            },
        ),
    ]
