# Generated by Django 5.2.8 on 2025-11-30 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_country_continent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("number_of_blogs", models.IntegerField(default=0)),
                ("number_of_views", models.IntegerField(default=0)),
                ("number_of_likes", models.IntegerField(default=0)),
                ("number_of_comments", models.IntegerField(default=0)),
                ("number_of_shares", models.IntegerField(default=0)),
                ("number_of_reactions", models.IntegerField(default=0)),
                ("number_of_followers", models.IntegerField(default=0)),
                ("number_of_following", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "ordering": ["-number_of_views"],
            },
        ),
    ]
