# Generated by Django 5.2.8 on 2025-12-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_blogview_created_at_blogview_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
