# Generated by Django 5.2.8 on 2025-11-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(default='Euro', max_length=128),
            preserve_default=False,
        ),
    ]
