# Generated by Django 5.2.8 on 2025-11-30 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_author_1_exists(apps, schema_editor):
    """Ensure Author with id=1 exists."""
    Author = apps.get_model("analytics", "Author")
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    # Ensure Author with id=1 exists
    # First, get or create User with id=1
    user_1, _ = User.objects.get_or_create(
        id=1,
        defaults={
            'username': 'default_author',
            'email': 'author@example.com',
        }
    )
    
    # Get or create Author with id=1 linked to user_1
    Author.objects.get_or_create(
        id=1,
        defaults={'user': user_1}
    )


def reverse_migration(apps, schema_editor):
    """Reverse: This is a one-way migration, cannot be reversed automatically."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Ensure Author with id=1 exists
        migrations.RunPython(
            ensure_author_1_exists,
            reverse_code=reverse_migration,
        ),
        # Step 2: For SQLite, temporarily disable foreign key checks
        migrations.RunSQL(
            sql="PRAGMA foreign_keys=OFF;",
            reverse_sql="PRAGMA foreign_keys=ON;",
        ),
        # Step 3: Set all blogs to author_id = 1 using raw SQL
        migrations.RunSQL(
            sql="UPDATE analytics_blog SET author_id = 1;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 4: Change the Blog.author field to point to Author
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="analytics.author",
            ),
        ),
        # Step 5: Re-enable foreign key checks for SQLite
        migrations.RunSQL(
            sql="PRAGMA foreign_keys=ON;",
            reverse_sql="PRAGMA foreign_keys=OFF;",
        ),
    ]
