# Generated by Django 5.2.8 on 2025-12-01 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_blogcreationtimeseriesaggregate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 12, 1, 9, 15, 52, 22896, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
